# Generated by Django 2.0.4 on 2018-07-06 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, unique=True)),
                ('long_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'points',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='value is not a valid hexadecimal color', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.AddField(
            model_name='point',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapApplication.Tag'),
        ),
    ]
