# Generated by Django 2.0.7 on 2018-08-25 22:31

import django.core.validators
from django.db import migrations, models
import mapApplication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(null=True)),
                ('credits', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'About and Credits',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='maps')),
                ('right_longitude', models.DecimalField(decimal_places=6, help_text='The longitude at the right side of the map', max_digits=9, null=True)),
                ('left_longitude', models.DecimalField(decimal_places=6, help_text='The longitude at the left side of the map', max_digits=9, null=True)),
                ('bottom_latitude', models.DecimalField(decimal_places=6, help_text='The latitude at the bottom of the map', max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, unique=True)),
                ('long_name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField(null=True)),
                ('long_description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('main_image', models.ImageField(null=True, upload_to=mapApplication.models.PathRename('0/'))),
                ('additional_image1', models.ImageField(blank=True, null=True, upload_to=mapApplication.models.PathRename('1/'))),
                ('additional_caption1', models.CharField(blank=True, max_length=100)),
                ('additional_image2', models.ImageField(blank=True, null=True, upload_to=mapApplication.models.PathRename('2/'))),
                ('additional_caption2', models.CharField(blank=True, max_length=100)),
                ('additional_image3', models.ImageField(blank=True, null=True, upload_to=mapApplication.models.PathRename('3/'))),
                ('additional_caption3', models.CharField(blank=True, max_length=100)),
                ('additional_image4', models.ImageField(blank=True, null=True, upload_to=mapApplication.models.PathRename('4/'))),
                ('additional_caption4', models.CharField(blank=True, max_length=100)),
                ('additional_image5', models.ImageField(blank=True, null=True, upload_to=mapApplication.models.PathRename('5/'))),
                ('additional_caption5', models.CharField(blank=True, max_length=100)),
                ('x', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(help_text='Enter a hexadecimal color value', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Value is not a valid hexadecimal color', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='tags',
            field=models.ManyToManyField(to='mapApplication.Tag'),
        ),
    ]
