# Generated by Django 2.0.4 on 2018-07-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApplication', '0002_auto_20180706_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='tags',
        ),
        migrations.AddField(
            model_name='point',
            name='tags',
            field=models.ManyToManyField(to='mapApplication.Tag'),
        ),
    ]
