# Generated by Django 2.0.7 on 2019-01-10 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapApplication', '0002_auto_20190110_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tourlocation',
            name='text',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='locations',
            field=models.ManyToManyField(through='mapApplication.TourLocation', to='mapApplication.Point'),
        ),
        migrations.AlterField(
            model_name='tourlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_link', to='mapApplication.Point'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
