# Generated by Django 2.0.4 on 2018-07-06 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApplication', '0003_auto_20180706_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='point',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='additionalImages'),
        ),
        migrations.AddField(
            model_name='point',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Enter a hexadecimal color value', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Value is not a valid hexadecimal color', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
