# Generated by Django 2.0.4 on 2018-07-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApplication', '0004_auto_20180706_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='additionalImages'),
        ),
        migrations.AlterField(
            model_name='point',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='heroImages'),
        ),
    ]
