# Generated by Django 2.0.4 on 2018-07-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApplication', '0005_auto_20180706_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='additional_images',
        ),
        migrations.AddField(
            model_name='point',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='otherImages'),
        ),
        migrations.AddField(
            model_name='point',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='otherImages'),
        ),
        migrations.AddField(
            model_name='point',
            name='additional_image3',
            field=models.ImageField(blank=True, null=True, upload_to='otherImages'),
        ),
        migrations.AddField(
            model_name='point',
            name='additional_image4',
            field=models.ImageField(blank=True, null=True, upload_to='otherImages'),
        ),
        migrations.AddField(
            model_name='point',
            name='additional_image5',
            field=models.ImageField(blank=True, null=True, upload_to='otherImages'),
        ),
        migrations.AlterField(
            model_name='point',
            name='main_image',
            field=models.ImageField(null=True, upload_to='mainImages'),
        ),
    ]
