# Generated by Django 2.0.4 on 2018-07-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApplication', '0006_auto_20180706_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
