# Generated by Django 2.0.4 on 2018-07-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApplication', '0007_auto_20180706_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='maps')),
                ('top_right_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('top_left_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('bottom_right_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('bottom_left_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('top_right_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('top_left_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('bottom_right_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('bottom_left_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
