# Generated by Django 2.0.4 on 2018-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApplication', '0010_auto_20180709_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='bottom_left_latitude',
        ),
        migrations.RemoveField(
            model_name='map',
            name='bottom_left_longitude',
        ),
        migrations.RemoveField(
            model_name='map',
            name='bottom_right_latitude',
        ),
        migrations.RemoveField(
            model_name='map',
            name='bottom_right_longitude',
        ),
        migrations.RemoveField(
            model_name='map',
            name='top_left_latitude',
        ),
        migrations.RemoveField(
            model_name='map',
            name='top_left_longitude',
        ),
        migrations.RemoveField(
            model_name='map',
            name='top_right_latitude',
        ),
        migrations.RemoveField(
            model_name='map',
            name='top_right_longitude',
        ),
        migrations.AddField(
            model_name='map',
            name='bottom_latitude',
            field=models.DecimalField(decimal_places=6, help_text='The latitude at the bottom of the map', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='left_longitude',
            field=models.DecimalField(decimal_places=6, help_text='The longitude at the left side of the map', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='right_longitude',
            field=models.DecimalField(decimal_places=6, help_text='The longitude at the right side of the map', max_digits=9, null=True),
        ),
    ]
