# Generated by Django 2.0.4 on 2018-07-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApplication', '0011_auto_20180710_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='x',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='y',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
