# Generated by Django 2.0.7 on 2018-07-28 00:31

from django.db import migrations, models
import mapApplication.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApplication', '0012_auto_20180711_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to=mapApplication.models.PathRename('1/')),
        ),
        migrations.AlterField(
            model_name='point',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to=mapApplication.models.PathRename('2/')),
        ),
        migrations.AlterField(
            model_name='point',
            name='additional_image3',
            field=models.ImageField(blank=True, null=True, upload_to=mapApplication.models.PathRename('3/')),
        ),
        migrations.AlterField(
            model_name='point',
            name='additional_image4',
            field=models.ImageField(blank=True, null=True, upload_to=mapApplication.models.PathRename('4/')),
        ),
        migrations.AlterField(
            model_name='point',
            name='additional_image5',
            field=models.ImageField(blank=True, null=True, upload_to=mapApplication.models.PathRename('5/')),
        ),
        migrations.AlterField(
            model_name='point',
            name='main_image',
            field=models.ImageField(null=True, upload_to=mapApplication.models.PathRename('0/')),
        ),
        migrations.AlterField(
            model_name='point',
            name='x',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='y',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
